# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JSCallNativeTest' do
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'WebViewJavascriptBridge'
pod 'JSPatch'
pod 'CocoaSecurity'
pod 'Cordova'
pod 'cordova-plugin-network-information', '~> 1.0.1'
pod 'cordova-plugin-file-transfer', '~> 1.3.0'
pod 'INTULocationManager'
end

target 'JSCallNativeTestTests' do

end

target 'JSCallNativeTestUITests' do

end

